service: default
runtime: nodejs10

env_variables:
  VUE_APP_API_URL: https://api-dot-ecstatic-splice-274712.an.r.appspot.com

handlers:
- url: /(.*\.(js|map|json|css|jpg|png|ico|svg|eot|ttf|woff|woff2))$
  static_files: dist/\1
  upload: dist/.*\.(js|map|json|css|jpg|png|ico|svg|eot|ttf|woff|woff2)$
  secure: always
- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
  secure: always